// Generated by CoffeeScript 1.6.3
(function() {
  Routes.ContextMap = (function() {
    function ContextMap(container, json, dataset_name, options) {
      if (options == null) {
        options = {};
      }
      this._json = json;
      this._dataset_name = dataset_name;
      this._options = options;
      this.group = container.append('g');
      console.log(container, this.group);
    }

    ContextMap.prototype.render = function() {
      var _this = this;
      return d3.json(this._json, function(error, json) {
        var calijson, map, path;
        calijson = topojson.feature(json, json.objects[_this._dataset_name]).features;
        path = d3.geo.path().projection(_this.projection());
        map = _this.group.append('g').attr('class', 'map');
        return map.selectAll('.zip').data(calijson).enter().append('path').attr('class', 'zip').attr('d', path).style('fill', 'none').style('stroke', _this._options.stroke || 'black').style('stroke-width', '0.1pt');
      });
    };

    ContextMap.prototype.projection = function(projection) {
      if (projection) {
        this._projection = projection;
        return this;
      }
      return this._projection;
    };

    return ContextMap;

  })();

}).call(this);
