// Generated by CoffeeScript 1.6.3
(function() {
  Routes.ContextMap = (function() {
    function ContextMap(json, dataset_name, options) {
      if (options == null) {
        options = {};
      }
      this._json = json;
      this._dataset_name = dataset_name;
      this._options = options;
      this.svg = d3.select('#map').append('svg');
    }

    ContextMap.prototype.render = function() {
      var _this = this;
      return d3.json(this._json, function(error, zips) {
        var calizips, map, path;
        console.log(zips);
        calizips = topojson.feature(zips, zips.objects[_this._dataset_name]).features;
        path = d3.geo.path().projection(_this.projection());
        map = _this.svg.append('g').attr('class', 'map');
        return map.selectAll('.zip').data(calizips).enter().append('path').attr('class', 'zip').attr('d', path).style('fill', 'none').style('stroke', 'black').style('stroke-width', '0.1pt');
      });
    };

    ContextMap.prototype.projection = function(projection) {
      if (projection) {
        this._projection = projection;
        return this;
      }
      return this._projection;
    };

    return ContextMap;

  })();

}).call(this);
