// Generated by CoffeeScript 1.6.3
(function() {
  var runTables;

  runTables = function() {
    window.table = new Routes.RouteTable('#container');
    return d3.json("../data/route_points.json", function(error, route_points) {
      return d3.json("../data/route_segments.json", function(error, route_segments) {
        var cm, height, id, projection, segments, sycamore_to_east_peak_segment_ids, width;
        table.route_points(route_points).route_segments(route_segments);
        sycamore_to_east_peak_segment_ids = [1, 2, 4, 5, 6];
        segments = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = sycamore_to_east_peak_segment_ids.length; _i < _len; _i++) {
            id = sycamore_to_east_peak_segment_ids[_i];
            _results.push(new Routes.RouteSegment(route_segments[id - 1]));
          }
          return _results;
        })();
        window.rsc = new Routes.RouteSegmentCollection(segments);
        rsc.name("Mt Tam from Mill Valley");
        table._route_segments.push(rsc);
        width = 1200;
        height = 800;
        projection = d3.geo.albers().scale(123000).rotate([122.4350, 0, 0]).center([0, 37.9800]).parallels([35, 36]).translate([width / 2, height / 2]);
        table.context_map('data/sf_marin_roads.json', 'marin_roads', {
          stroke: 'red'
        }).projection(projection).render();
        cm = table.context_map('data/bayarea.json', 'ba');
        cm.projection(projection).render();
        return table.render();
      });
    });
  };

  runTables();

}).call(this);
