// Generated by CoffeeScript 1.6.3
(function() {
  Routes.RouteSegment = (function() {
    function RouteSegment(json) {
      this.id = json.id;
      this._reversed = false;
      this._miles = json.miles;
      this._elevation = json.elevation;
      this._reverse_elevation = json.reverse_elevation;
      this._start_point_id = json.start_point_id;
      this._end_point_id = json.end_point_id;
    }

    RouteSegment.prototype.miles = function() {
      return this._miles;
    };

    RouteSegment.prototype.elevation = function() {
      if (this._reversed) {
        return this._reverse_elevation;
      } else {
        return this._elevation;
      }
    };

    RouteSegment.prototype.reverse_elevation = function() {
      if (this._reversed) {
        return this._elevation;
      } else {
        return this._reverse_elevation;
      }
    };

    RouteSegment.prototype.start_point_id = function() {
      if (this._reversed) {
        return this._end_point_id;
      } else {
        return this._start_point_id;
      }
    };

    RouteSegment.prototype.end_point_id = function() {
      if (this._reversed) {
        return this._start_point_id;
      } else {
        return this._end_point_id;
      }
    };

    RouteSegment.prototype.reverse = function() {
      this._reversed = !this._reversed;
      return this;
    };

    RouteSegment.prototype.components = function() {
      return [this];
    };

    RouteSegment.prototype.name = function() {
      return null;
    };

    return RouteSegment;

  })();

}).call(this);
